import * as S from 'effect/Schema'

// Define all block types as a const array for type safety
export const blockTypes = [
  'air',
  'stone',
  'dirt',
  'grass',
  'cobblestone',
  'wood',
  'sand',
  'gravel',
  'gold_ore',
  'iron_ore',
  'coal_ore',
  'log',
  'oakLog',
  'leaves',
  'glass',
  'plank',
  'brick',
  'lapis_ore',
  'lapis_block',
  'sandstone',
  'wool',
  'flower',
  'mushroom',
  'tnt',
  'bookshelf',
  'mossy_cobblestone',
  'obsidian',
  'diamond_ore',
  'diamond_block',
  'crafting_table',
  'furnace',
  'redstone_ore',
  'snow',
  'ice',
  'cactus',
  'clay',
  'jukebox',
  'pumpkin',
  'netherrack',
  'glowstone',
  'jack_o_lantern',
  'cake',
  'bedrock',
  'water',
  'lava',
] as const

export type BlockType = (typeof blockTypes)[number]

export const BlockType = S.Literal(...blockTypes)
export const BlockTypeSchema = BlockType