import type { InventoryItem } from '@ts-minecraft/core'

export const DURABLE_ITEMS = [
  'WOODEN_SWORD',
  'WOODEN_PICKAXE',
  'WOODEN_HOE',
  'WOODEN_AXE',
  'WOODEN_SHOVEL',
  'STONE_SWORD',
  'STONE_PICKAXE',
  'STONE_HOE',
  'STONE_AXE',
  'STONE_SHOVEL',
  'IRON_SWORD',
  'IRON_PICKAXE',
  'IRON_HOE',
  'IRON_AXE',
  'IRON_SHOVEL',
  'DIAMOND_SWORD',
  'GOLD_SWORD',
  'DIAMOND_PICKAXE',
  'GOLD_PICKAXE',
  'DIAMOND_HOE',
  'GOLD_HOE',
  'DIAMOND_AXE',
  'GOLD_AXE',
  'DIAMOND_SHOVEL',
  'GOLD_SHOVEL',
  'FISHING_ROD',
  'BOW',
  'SHIELD',
  'SHEARS',
  'LEATHER_HELMET',
  'LEATHER_CHESTPLATE',
  'LEATHER_LEGGINGS',
  'LEATHER_BOOTS',
  'IRON_HELMET',
  'IRON_CHESTPLATE',
  'IRON_LEGGINGS',
  'IRON_BOOTS',
  'GOLD_HELMET',
  'GOLD_CHESTPLATE',
  'GOLD_LEGGINGS',
  'GOLD_BOOTS',
  'DIAMOND_HELMET',
  'DIAMOND_CHESTPLATE',
  'DIAMOND_LEGGINGS',
  'DIAMOND_BOOTS',
] as const satisfies ReadonlyArray<InventoryItem>

export type DurableItem = typeof DURABLE_ITEMS[number]

// Tool/weapon/armor durability (Phase 12). Pure domain data: the maximum number
// of uses before a durable item breaks. Values match Minecraft Java Edition
// material tiers; swords and pickaxes of the same material share a budget.
//
// This table is the SINGLE SOURCE OF TRUTH for durable item types:
// item-stack's non-stackable set is derived from DURABLE_ITEMS, so a new durable
// item added here is automatically both damageable and non-stackable.
export const TOOL_MAX_DURABILITY: Record<DurableItem, number> = {
  // Tools & weapons — Minecraft Java Edition values
  WOODEN_SWORD: 59,
  WOODEN_PICKAXE: 59,
  WOODEN_HOE: 59,
  WOODEN_AXE: 59,
  WOODEN_SHOVEL: 59,
  STONE_SWORD: 131,
  STONE_PICKAXE: 131,
  STONE_HOE: 131,
  STONE_AXE: 131,
  STONE_SHOVEL: 131,
  IRON_SWORD: 250,
  IRON_PICKAXE: 250,
  IRON_HOE: 250,
  IRON_AXE: 250,
  IRON_SHOVEL: 250,
  DIAMOND_SWORD: 1561,
  GOLD_SWORD: 32,
  DIAMOND_PICKAXE: 1561,
  GOLD_PICKAXE: 32,
  DIAMOND_HOE: 1561,
  GOLD_HOE: 32,
  DIAMOND_AXE: 1561,
  GOLD_AXE: 32,
  DIAMOND_SHOVEL: 1561,
  GOLD_SHOVEL: 32,
  FISHING_ROD: 64,
  BOW: 384,
  SHIELD: 336,
  SHEARS: 238, // FR R11 — vanilla Java shears; damaged once per shear (right-click)
  // Armor — each piece has its own durability budget (Minecraft Java Edition)
  LEATHER_HELMET: 55,
  LEATHER_CHESTPLATE: 80,
  LEATHER_LEGGINGS: 75,
  LEATHER_BOOTS: 65,
  IRON_HELMET: 165,
  IRON_CHESTPLATE: 240,
  IRON_LEGGINGS: 225,
  IRON_BOOTS: 195,
  GOLD_HELMET: 77,
  GOLD_CHESTPLATE: 112,
  GOLD_LEGGINGS: 105,
  GOLD_BOOTS: 91,
  DIAMOND_HELMET: 363,
  DIAMOND_CHESTPLATE: 528,
  DIAMOND_LEGGINGS: 495,
  DIAMOND_BOOTS: 429,
}
