import type { ItemType } from '@ts-minecraft/core'
import type { EnchantmentLevel, EnchantmentType } from './enchantment.types'

// ─── Validity ────────────────────────────────────────────────────────────────

export const MAX_LEVEL: Record<EnchantmentType, EnchantmentLevel> = {
  SHARPNESS: 5,
  SMITE: 5,
  BANE_OF_ARTHROPODS: 5,
  KNOCKBACK: 2,
  PROTECTION: 4,
  PROJECTILE_PROTECTION: 4,
  FIRE_PROTECTION: 4,
  BLAST_PROTECTION: 4,
  FEATHER_FALLING: 4,
  RESPIRATION: 3,
  EFFICIENCY: 5,
  FORTUNE: 3,
  SILK_TOUCH: 1,
  UNBREAKING: 3,
  LOOTING: 3,
  INFINITY: 1,
  POWER: 5,
  PUNCH: 2,
  LURE: 3,
  LUCK_OF_THE_SEA: 3,
}

// ─── Fortune multipliers ─────────────────────────────────────────────────────

export const FORTUNE_MULTIPLIERS: Record<EnchantmentLevel, number> = { 1: 1.33, 2: 1.75, 3: 2.5, 4: 2.5, 5: 2.5 }

// ─── Applicable items ────────────────────────────────────────────────────────

// Which item types may carry each enchantment. Used by the enchanting service
// to validate requests.
export const APPLICABLE_TO: Partial<Record<EnchantmentType, ReadonlySet<ItemType>>> = {
  SHARPNESS: new Set(['WOODEN_SWORD', 'STONE_SWORD', 'IRON_SWORD', 'DIAMOND_SWORD',
    'WOODEN_AXE', 'STONE_AXE', 'IRON_AXE', 'DIAMOND_AXE']),
  SMITE: new Set(['WOODEN_SWORD', 'STONE_SWORD', 'IRON_SWORD', 'DIAMOND_SWORD']),
  BANE_OF_ARTHROPODS: new Set(['WOODEN_SWORD', 'STONE_SWORD', 'IRON_SWORD', 'DIAMOND_SWORD']),
  KNOCKBACK: new Set(['WOODEN_SWORD', 'STONE_SWORD', 'IRON_SWORD', 'DIAMOND_SWORD']),
  PROTECTION: new Set(['LEATHER_HELMET', 'LEATHER_CHESTPLATE', 'LEATHER_LEGGINGS', 'LEATHER_BOOTS',
    'IRON_HELMET', 'IRON_CHESTPLATE', 'IRON_LEGGINGS', 'IRON_BOOTS',
    'DIAMOND_HELMET', 'DIAMOND_CHESTPLATE', 'DIAMOND_LEGGINGS', 'DIAMOND_BOOTS']),
  PROJECTILE_PROTECTION: new Set(['LEATHER_HELMET', 'LEATHER_CHESTPLATE', 'LEATHER_LEGGINGS', 'LEATHER_BOOTS',
    'IRON_HELMET', 'IRON_CHESTPLATE', 'IRON_LEGGINGS', 'IRON_BOOTS',
    'DIAMOND_HELMET', 'DIAMOND_CHESTPLATE', 'DIAMOND_LEGGINGS', 'DIAMOND_BOOTS']),
  FIRE_PROTECTION: new Set(['LEATHER_HELMET', 'LEATHER_CHESTPLATE', 'LEATHER_LEGGINGS', 'LEATHER_BOOTS',
    'IRON_HELMET', 'IRON_CHESTPLATE', 'IRON_LEGGINGS', 'IRON_BOOTS',
    'DIAMOND_HELMET', 'DIAMOND_CHESTPLATE', 'DIAMOND_LEGGINGS', 'DIAMOND_BOOTS']),
  BLAST_PROTECTION: new Set(['LEATHER_HELMET', 'LEATHER_CHESTPLATE', 'LEATHER_LEGGINGS', 'LEATHER_BOOTS',
    'IRON_HELMET', 'IRON_CHESTPLATE', 'IRON_LEGGINGS', 'IRON_BOOTS',
    'DIAMOND_HELMET', 'DIAMOND_CHESTPLATE', 'DIAMOND_LEGGINGS', 'DIAMOND_BOOTS']),
  FEATHER_FALLING: new Set(['LEATHER_BOOTS', 'IRON_BOOTS', 'DIAMOND_BOOTS']),
  RESPIRATION: new Set(['LEATHER_HELMET', 'IRON_HELMET', 'DIAMOND_HELMET']),
  EFFICIENCY: new Set(['WOODEN_PICKAXE', 'STONE_PICKAXE', 'IRON_PICKAXE', 'DIAMOND_PICKAXE',
    'WOODEN_SHOVEL', 'STONE_SHOVEL', 'IRON_SHOVEL', 'DIAMOND_SHOVEL',
    'WOODEN_AXE', 'STONE_AXE', 'IRON_AXE', 'DIAMOND_AXE',
    'WOODEN_HOE', 'STONE_HOE', 'IRON_HOE', 'DIAMOND_HOE']),
  FORTUNE: new Set(['WOODEN_PICKAXE', 'STONE_PICKAXE', 'IRON_PICKAXE', 'DIAMOND_PICKAXE',
    'WOODEN_SHOVEL', 'STONE_SHOVEL', 'IRON_SHOVEL', 'DIAMOND_SHOVEL']),
  SILK_TOUCH: new Set(['WOODEN_PICKAXE', 'STONE_PICKAXE', 'IRON_PICKAXE', 'DIAMOND_PICKAXE',
    'WOODEN_SHOVEL', 'STONE_SHOVEL', 'IRON_SHOVEL', 'DIAMOND_SHOVEL',
    'WOODEN_AXE', 'STONE_AXE', 'IRON_AXE', 'DIAMOND_AXE']),
  UNBREAKING: new Set(['WOODEN_SWORD', 'STONE_SWORD', 'IRON_SWORD', 'DIAMOND_SWORD',
    'WOODEN_PICKAXE', 'STONE_PICKAXE', 'IRON_PICKAXE', 'DIAMOND_PICKAXE',
    'WOODEN_SHOVEL', 'STONE_SHOVEL', 'IRON_SHOVEL', 'DIAMOND_SHOVEL',
    'WOODEN_AXE', 'STONE_AXE', 'IRON_AXE', 'DIAMOND_AXE',
    'WOODEN_HOE', 'STONE_HOE', 'IRON_HOE', 'DIAMOND_HOE',
    'LEATHER_HELMET', 'LEATHER_CHESTPLATE', 'LEATHER_LEGGINGS', 'LEATHER_BOOTS',
    'IRON_HELMET', 'IRON_CHESTPLATE', 'IRON_LEGGINGS', 'IRON_BOOTS',
    'DIAMOND_HELMET', 'DIAMOND_CHESTPLATE', 'DIAMOND_LEGGINGS', 'DIAMOND_BOOTS',
    'BOW', 'FISHING_ROD', 'SHIELD']),
  LOOTING: new Set(['WOODEN_SWORD', 'STONE_SWORD', 'IRON_SWORD', 'DIAMOND_SWORD']),
  INFINITY: new Set(['BOW']),
  POWER: new Set(['BOW']),
  PUNCH: new Set(['BOW']),
  LURE: new Set(['FISHING_ROD']),
  LUCK_OF_THE_SEA: new Set(['FISHING_ROD']),
}
