import { defineConfig } from 'vitest/config'
import { resolve } from 'path'

export default defineConfig({
  test: {
    environment: 'node',
    globals: false,
    pool: 'forks',
    poolOptions: {
      forks: {
        maxForks: '50%',
        minForks: 1,
        isolate: true,
        singleFork: false,
      },
    },
    include: ['test/**/*.{test,spec}.?(c|m)[jt]s?(x)', 'packages/*/{application,infrastructure,domain,presentation}/**/*.{test,spec}.?(c|m)[jt]s?(x)', 'packages/presentation/**/*.{test,spec}.?(c|m)[jt]s?(x)', 'packages/*/test/**/*.{test,spec}.?(c|m)[jt]s?(x)'],
    exclude: ['**/node_modules/**', '**/dist/**', '**/.git/**', '**/coverage/**'],
    testTimeout: 10000,
    hookTimeout: 10000,
    teardownTimeout: 5000,
    slowTestThreshold: 300,
    fileParallelism: true,
    sequence: {
      seed: 0,
      hooks: 'stack',
    },
    reporters: ['default'],
    coverage: {
      provider: 'v8',
      enabled: false,
      include: ['packages/*/{application,infrastructure,domain,presentation}/**/*.{ts,tsx}'],
      exclude: [
        // TEST_UTILS: build/dependency artifacts and generated declarations are outside source coverage.
        'dist/**',
        'node_modules/**',
        '**/*.d.ts',
        // TEST_UTILS: config/test/helper files are validated by typecheck, lint, and/or consuming tests.
        '**/*.config.{js,ts}',
        '**/*.test.{js,ts}',
        '**/*.spec.{js,ts}',
        '**/*.property.test.{js,ts}',
        '**/*-test-utils.ts',
        '**/*test-utils.ts',
        // TEST_UTILS: test-data builders (validated by their consuming tests).
        'packages/core/domain/builders.ts',

        // BARREL: package or feature entry points that only aggregate/re-export covered modules.
        '**/index.ts',
        '**/*schemas.ts',
        '**/*ports.ts',
        'packages/core/domain/errors.ts',

        // PURE_TYPE: declarations only; no executable source behavior to cover in Vitest.
        'packages/entity/domain/mob/drop.ts',
        'packages/inventory/domain/furnace-state.ts',
        'packages/world/domain/terrain/generator-types.ts',
        'packages/world/domain/biome-generator-port.ts',
        'packages/rendering/application/chunk-count-port.ts',
        'packages/app/application/frame/types.ts',
        'packages/inventory/domain/enchantment.types.ts',
        'packages/app/application/debug-feature-flags.types.ts',
        'packages/worker/domain/meshing-worker-pool-types.ts',

        // BROWSER_ONLY: browser entry-point wiring; contract marker in e2e/contracts/browser-api-contracts.e2e.ts.
        'src/main.ts',
        'packages/app/application/main/**',
        'packages/app/application/frame/frame-maintenance.ts',
        'packages/app/application/frame/stages/interaction-break-handler.ts',
        'packages/app/application/frame/stages/interaction-melee-handler.ts',
        'packages/app/application/frame/stages/interaction-bow-handler.ts',
        'packages/app/application/frame/stages/interaction-item-use-handler.ts',

        // WORKER: Web Worker runtime APIs; contract marker in e2e/contracts/browser-api-contracts.e2e.ts.
        '**/workers/**',
        'packages/worker/infrastructure/terrain-worker.ts',
        'packages/worker/infrastructure/terrain-worker-pool.ts',
        'packages/worker/infrastructure/terrain-worker-pool-helpers.ts',
        'packages/worker/infrastructure/terrain-worker-pool-port-layer.ts',

        // BROWSER_ONLY: WebGL/THREE.js infrastructure requiring canvas/WebGL or browser loaders.
        '**/god-rays-pass.ts',
        'packages/rendering/infrastructure/meshing/chunk-mesh.ts',
        'packages/rendering/infrastructure/meshing/chunk-mesh-geometry.ts',
        'packages/rendering/infrastructure/meshing/chunk-mesh-materials.ts',
        'packages/rendering/infrastructure/meshing/lod-simplification.ts',
        'packages/rendering/infrastructure/meshing/subregion-greedy-splice.ts',
        'packages/rendering/infrastructure/entity/entity-instance-pool.ts',
        'packages/rendering/infrastructure/entity/entity-renderer.ts',
        'packages/rendering/infrastructure/perf/gpu-timer-service.ts',
        'packages/rendering/infrastructure/renderer/world-renderer-chunk-sync.ts',
        'packages/rendering/infrastructure/renderer/world-renderer-chunk-update.ts',
        'packages/rendering/infrastructure/renderer/world-renderer-refraction-ratio.ts',
        'packages/rendering/infrastructure/renderer/world-renderer.ts',
        'packages/rendering/infrastructure/renderer/renderer-service.ts',
        'packages/rendering/infrastructure/textures/texture-loader.ts',

        // BROWSER_ONLY: browser performance, audio, DOM, and IndexedDB APIs.
        '**/perf-marks.ts',
        'packages/rendering/application/perf-flags.ts',
        'packages/world/infrastructure/idb-utils.ts',
        'packages/world/infrastructure/storage-service.ts',
        'packages/world/infrastructure/storage-error-mapping.ts',
        'packages/world/infrastructure/storage-idb-model.ts',
        'packages/world/infrastructure/storage-serialization.ts',
        'packages/game/infrastructure/audio-engine.ts',
        'packages/game/infrastructure/audio-context-helpers.ts',
        'packages/game/application/settings-service.ts',
        'packages/entity/application/redstone/redstone-service.ts',
        'packages/block/domain/light.ts',
        'packages/world/application/biome-service.ts',
        'packages/world/application/chunk-manager-ops.ts',
        'packages/world/application/chunk-manager-service-ops.ts',
        'packages/world/application/light-engine-service.ts',
        'packages/world/domain/block-light-bfs.ts',
        'packages/world/domain/chunk-coord-utils.ts',
        'packages/world/domain/light-engine-model.ts',
        'packages/world/domain/sky-light-bfs.ts',
        'packages/world/domain/terrain/generator-pipeline.ts',
        'packages/core/domain/math/camera-port.ts',
        'packages/presentation/inventory/inventory-renderer-click-handler.ts',
        '**/pause-menu.ts',
        '**/death-screen.ts',
        '**/input-service.ts',
        'packages/presentation/hud/debug-overlay.ts',
        'packages/presentation/menu/main-menu.ts',
        'packages/presentation/menu/confirm-dialog.ts',
        'packages/presentation/settings/settings-overlay.ts',
        'packages/rendering/presentation/perf-hud.ts',
        'packages/rendering/presentation/perf-hud-counters.ts',

        // WORKER: meshing worker runtime APIs; contract marker in e2e/contracts/browser-api-contracts.e2e.ts.
        'packages/worker/infrastructure/meshing/meshing-worker.ts',
        'packages/worker/infrastructure/meshing/meshing-worker-pool.ts',
        'packages/worker/infrastructure/meshing/meshing-worker-pool-protocol.ts',
        'packages/worker/infrastructure/meshing/meshing-worker-sync.ts',
      ],
      all: true,
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      // 99% enforcement for Node-testable domain/application code (enforced by test:coverage).
      // Browser/WebGL/Worker/IDB infrastructure files are documented exclusions above.
      thresholds: {
        branches: 99,
        functions: 99,
        lines: 99,
        statements: 99,
      },
    },
    deps: {},
  },
  resolve: {
    alias: {
      '@test': resolve(__dirname, 'test'),
      '@test/harness': resolve(__dirname, 'test/harness'),
      // @ts-minecraft/* workspace package aliases
      '@ts-minecraft/core': resolve(__dirname, 'packages/core'),
      '@ts-minecraft/block': resolve(__dirname, 'packages/block'),
      '@ts-minecraft/entity': resolve(__dirname, 'packages/entity'),
      '@ts-minecraft/inventory': resolve(__dirname, 'packages/inventory'),
      '@ts-minecraft/network': resolve(__dirname, 'packages/network'),
      '@ts-minecraft/world': resolve(__dirname, 'packages/world'),
      '@ts-minecraft/game': resolve(__dirname, 'packages/game'),
      '@ts-minecraft/rendering/particles/particle-system': resolve(__dirname, 'packages/rendering/infrastructure/particles/particle-system'),
      '@ts-minecraft/rendering': resolve(__dirname, 'packages/rendering'),
      '@ts-minecraft/worker': resolve(__dirname, 'packages/worker'),
      '@ts-minecraft/presentation': resolve(__dirname, 'packages/presentation'),
      '@ts-minecraft/app/frame-handler.config': resolve(__dirname, 'packages/app/application/frame-handler.config'),
      '@ts-minecraft/app/frame-handler': resolve(__dirname, 'packages/app/application/frame-handler'),
      '@ts-minecraft/app/frame': resolve(__dirname, 'packages/app/application/frame'),
      '@ts-minecraft/app/main.config': resolve(__dirname, 'packages/app/application/main.config'),
      '@ts-minecraft/app/main': resolve(__dirname, 'packages/app/application/main'),
      '@ts-minecraft/app': resolve(__dirname, 'packages/app'),
    },
  },
  esbuild: {
    target: 'node22',
    format: 'esm',
    platform: 'node',
  },
})
