import { defineConfig } from 'vitest/config'
import { resolve } from 'path'

export default defineConfig({
  test: {
    environment: 'node',
    globals: false,
    pool: 'forks',
    poolOptions: {
      forks: {
        maxForks: '50%',
        minForks: 1,
        isolate: true,
        singleFork: false,
      },
    },
    include: ['test/**/*.{test,spec}.?(c|m)[jt]s?(x)', 'packages/*/{application,infrastructure,domain,presentation}/**/*.{test,spec}.?(c|m)[jt]s?(x)'],
    exclude: ['**/node_modules/**', '**/dist/**', '**/.git/**', '**/coverage/**'],
    testTimeout: 10000,
    hookTimeout: 10000,
    slowTestThreshold: 300,
    fileParallelism: true,
    sequence: {
      seed: 0,
      hooks: 'stack',
    },
    reporters: ['default'],
    coverage: {
      provider: 'v8',
      enabled: false,
      include: ['packages/*/{application,infrastructure,domain,presentation}/**/*.{ts,tsx}'],
      exclude: [
        'dist/**',
        'node_modules/**',
        '**/*.d.ts',
        '**/*.config.{js,ts}',
        '**/*.test.{js,ts}',
        '**/*.spec.{js,ts}',
        '**/*.property.test.{js,ts}',
        '**/index.ts',
        // Browser-only entrypoints and WebGL passes — not runnable in Node.js
        '**/workers/**',
        '**/god-rays-pass.ts',
        '**/perf-marks.ts',
        'src/main.ts',
        // DOM-heavy presentation files with no meaningful unit-test surface
        '**/pause-menu.ts',
        '**/death-screen.ts',
        '**/input-service.ts',
      ],
      all: true,
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
    deps: {
      optimizer: {
        ssr: {
          enabled: true,
          include: ['effect'],
        },
      },
    },
  },
  resolve: {
    alias: {
      '@test': resolve(__dirname, 'test'),
      // @ts-minecraft/* workspace package aliases
      '@ts-minecraft/kernel': resolve(__dirname, 'packages/kernel'),
      '@ts-minecraft/domain': resolve(__dirname, 'packages/domain'),
      '@ts-minecraft/noise-generator': resolve(__dirname, 'packages/noise-generator'),
      '@ts-minecraft/block-storage': resolve(__dirname, 'packages/block-storage'),
      '@ts-minecraft/physics-engine': resolve(__dirname, 'packages/physics-engine'),
      '@ts-minecraft/terrain-generator': resolve(__dirname, 'packages/terrain-generator'),
      '@ts-minecraft/biome-classifier': resolve(__dirname, 'packages/biome-classifier'),
      '@ts-minecraft/chunk-manager': resolve(__dirname, 'packages/chunk-manager'),
      '@ts-minecraft/world-renderer/particles/particle-system': resolve(__dirname, 'packages/world-renderer/infrastructure/particles/particle-system'),
      '@ts-minecraft/world-renderer': resolve(__dirname, 'packages/world-renderer'),
      '@ts-minecraft/block-service': resolve(__dirname, 'packages/block-service'),
      '@ts-minecraft/fluid-simulation': resolve(__dirname, 'packages/fluid-simulation'),
      '@ts-minecraft/light-engine': resolve(__dirname, 'packages/light-engine'),
      '@ts-minecraft/redstone-circuit': resolve(__dirname, 'packages/redstone-circuit'),
      '@ts-minecraft/player-controller': resolve(__dirname, 'packages/player-controller'),
      '@ts-minecraft/camera-controller': resolve(__dirname, 'packages/camera-controller'),
      '@ts-minecraft/input-handler': resolve(__dirname, 'packages/input-handler'),
      '@ts-minecraft/inventory-system': resolve(__dirname, 'packages/inventory-system'),
      '@ts-minecraft/hotbar-system': resolve(__dirname, 'packages/hotbar-system'),
      '@ts-minecraft/crafting-system': resolve(__dirname, 'packages/crafting-system'),
      '@ts-minecraft/furnace-system': resolve(__dirname, 'packages/furnace-system'),
      '@ts-minecraft/game-mode': resolve(__dirname, 'packages/game-mode'),
      '@ts-minecraft/settings-manager': resolve(__dirname, 'packages/settings-manager'),
      '@ts-minecraft/day-night-cycle': resolve(__dirname, 'packages/day-night-cycle'),
      '@ts-minecraft/audio-engine': resolve(__dirname, 'packages/audio-engine'),
      '@ts-minecraft/entity-manager': resolve(__dirname, 'packages/entity-manager'),
      '@ts-minecraft/village-system': resolve(__dirname, 'packages/village-system'),
      '@ts-minecraft/trading-system': resolve(__dirname, 'packages/trading-system'),
      '@ts-minecraft/game-session': resolve(__dirname, 'packages/game-session'),
      '@ts-minecraft/game-loop': resolve(__dirname, 'packages/game-loop'),
      '@ts-minecraft/app/frame-handler.config': resolve(__dirname, 'packages/app/application/frame-handler.config'),
      '@ts-minecraft/app/frame-handler': resolve(__dirname, 'packages/app/application/frame-handler'),
      '@ts-minecraft/app/frame': resolve(__dirname, 'packages/app/application/frame'),
      '@ts-minecraft/app/main.config': resolve(__dirname, 'packages/app/application/main.config'),
      '@ts-minecraft/app/main': resolve(__dirname, 'packages/app/application/main'),
      '@ts-minecraft/app': resolve(__dirname, 'packages/app'),
      '@ts-minecraft/terrain-worker-pool': resolve(__dirname, 'packages/terrain-worker-pool'),
      '@ts-minecraft/environment': resolve(__dirname, 'packages/environment'),
      '@ts-minecraft/perf-hud': resolve(__dirname, 'packages/perf-hud'),
    },
  },
  esbuild: {
    target: 'node22',
    format: 'esm',
    platform: 'node',
  },
})
