import { defineConfig } from 'vitest/config'
import { resolve } from 'path'

export default defineConfig({
  test: {
    environment: 'node',
    globals: false,
    pool: 'forks',
    poolOptions: {
      forks: {
        maxForks: '50%',
        minForks: 1,
        isolate: true,
        singleFork: false,
      },
    },
    include: ['src/**/*.{test,spec}.?(c|m)[jt]s?(x)', 'test/**/*.{test,spec}.?(c|m)[jt]s?(x)', 'packages/*/src/**/*.{test,spec}.?(c|m)[jt]s?(x)'],
    exclude: ['**/node_modules/**', '**/dist/**', '**/.git/**', '**/coverage/**'],
    testTimeout: 10000,
    hookTimeout: 10000,
    slowTestThreshold: 300,
    fileParallelism: true,
    sequence: {
      seed: 0,
      hooks: 'stack',
    },
    reporters: ['default'],
    coverage: {
      provider: 'v8',
      enabled: false,
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'dist/**',
        'node_modules/**',
        '**/*.d.ts',
        '**/*.config.{js,ts}',
        '**/*.test.{js,ts}',
        '**/*.spec.{js,ts}',
      ],
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
    deps: {
      optimizer: {
        ssr: {
          enabled: true,
          include: ['effect'],
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      '@/application': resolve(__dirname, 'src/application'),
      '@/infrastructure': resolve(__dirname, 'src/infrastructure'),
      '@/presentation': resolve(__dirname, 'src/presentation'),
      '@test': resolve(__dirname, 'test'),
      // @ts-minecraft/* workspace package aliases
      '@ts-minecraft/kernel': resolve(__dirname, 'packages/kernel/src'),
      '@ts-minecraft/domain': resolve(__dirname, 'packages/domain/src'),
      '@ts-minecraft/noise-generator': resolve(__dirname, 'packages/noise-generator/src'),
      '@ts-minecraft/block-storage': resolve(__dirname, 'packages/block-storage/src'),
      '@ts-minecraft/physics-engine': resolve(__dirname, 'packages/physics-engine/src'),
      '@ts-minecraft/terrain-generator': resolve(__dirname, 'packages/terrain-generator/src'),
      '@ts-minecraft/biome-classifier': resolve(__dirname, 'packages/biome-classifier/src'),
      '@ts-minecraft/chunk-manager': resolve(__dirname, 'packages/chunk-manager/src'),
      '@ts-minecraft/world-renderer': resolve(__dirname, 'packages/world-renderer/src'),
      '@ts-minecraft/block-service': resolve(__dirname, 'packages/block-service/src'),
      '@ts-minecraft/fluid-simulation': resolve(__dirname, 'packages/fluid-simulation/src'),
      '@ts-minecraft/light-engine': resolve(__dirname, 'packages/light-engine/src'),
      '@ts-minecraft/redstone-circuit': resolve(__dirname, 'packages/redstone-circuit/src'),
      '@ts-minecraft/player-controller': resolve(__dirname, 'packages/player-controller/src'),
      '@ts-minecraft/camera-controller': resolve(__dirname, 'packages/camera-controller/src'),
      '@ts-minecraft/input-handler': resolve(__dirname, 'packages/input-handler/src'),
      '@ts-minecraft/inventory-system': resolve(__dirname, 'packages/inventory-system/src'),
      '@ts-minecraft/hotbar-system': resolve(__dirname, 'packages/hotbar-system/src'),
      '@ts-minecraft/crafting-system': resolve(__dirname, 'packages/crafting-system/src'),
      '@ts-minecraft/furnace-system': resolve(__dirname, 'packages/furnace-system/src'),
      '@ts-minecraft/game-mode': resolve(__dirname, 'packages/game-mode/src'),
      '@ts-minecraft/settings-manager': resolve(__dirname, 'packages/settings-manager/src'),
      '@ts-minecraft/day-night-cycle': resolve(__dirname, 'packages/day-night-cycle/src'),
      '@ts-minecraft/audio-engine': resolve(__dirname, 'packages/audio-engine/src'),
      '@ts-minecraft/entity-manager': resolve(__dirname, 'packages/entity-manager/src'),
      '@ts-minecraft/village-system': resolve(__dirname, 'packages/village-system/src'),
      '@ts-minecraft/trading-system': resolve(__dirname, 'packages/trading-system/src'),
      '@ts-minecraft/game-session': resolve(__dirname, 'packages/game-session/src'),
      '@ts-minecraft/game-loop': resolve(__dirname, 'packages/game-loop/src'),
      '@ts-minecraft/app': resolve(__dirname, 'packages/app/src'),
      '@ts-minecraft/terrain-worker-pool': resolve(__dirname, 'packages/terrain-worker-pool/src'),
      '@ts-minecraft/environment': resolve(__dirname, 'packages/environment/src'),
      '@ts-minecraft/perf-hud': resolve(__dirname, 'packages/perf-hud/src'),
    },
  },
  esbuild: {
    target: 'node22',
    format: 'esm',
    platform: 'node',
  },
})
