import { Block } from './block'
import { BlockId } from '@/shared/kernel'

export const defaultBlockProperties = {
  hardness: 50,
  transparency: false,
  solid: true,
  emissive: false,
  friction: 0.6,
}

export const defaultBlockFaces = {
  top: true,
  bottom: true,
  north: true,
  south: true,
  east: true,
  west: true,
}

const makeBlockId = (id: string) => BlockId.make(id)

export const initialBlocks: ReadonlyArray<Block> = [
  new Block({
    id: makeBlockId('block:air'),
    type: 'AIR',
    properties: {
      hardness: 0,
      transparency: true,
      solid: false,
      emissive: false,
      friction: 0,
    },
    faces: {
      top: false,
      bottom: false,
      north: false,
      south: false,
      east: false,
      west: false,
    },
  }),
  new Block({
    id: makeBlockId('block:dirt'),
    type: 'DIRT',
    properties: defaultBlockProperties,
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:stone'),
    type: 'STONE',
    properties: {
      ...defaultBlockProperties,
      hardness: 100,
      friction: 0.8,
    },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:wood'),
    type: 'WOOD',
    properties: {
      ...defaultBlockProperties,
      hardness: 30,
    },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:grass'),
    type: 'GRASS',
    properties: {
      ...defaultBlockProperties,
      hardness: 20,
      emissive: false,
    },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:sand'),
    type: 'SAND',
    properties: {
      ...defaultBlockProperties,
      hardness: 10,
      friction: 0.5,
    },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:water'),
    type: 'WATER',
    properties: {
      ...defaultBlockProperties,
      hardness: 0,
      transparency: true,
      solid: false,
      friction: 0,
    },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:leaves'),
    type: 'LEAVES',
    properties: {
      ...defaultBlockProperties,
      hardness: 5,
      transparency: true,
    },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:glass'),
    type: 'GLASS',
    properties: {
      ...defaultBlockProperties,
      hardness: 5,
      transparency: true,
    },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:snow'),
    type: 'SNOW',
    properties: { hardness: 5, transparency: false, solid: true, emissive: false, friction: 0.3 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:gravel'),
    type: 'GRAVEL',
    properties: { hardness: 15, transparency: false, solid: true, emissive: false, friction: 0.5 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:cobblestone'),
    type: 'COBBLESTONE',
    properties: { hardness: 80, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:granite'),
    type: 'GRANITE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:diorite'),
    type: 'DIORITE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:andesite'),
    type: 'ANDESITE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:deepslate'),
    type: 'DEEPSLATE',
    properties: { hardness: 95, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:bedrock'),
    type: 'BEDROCK',
    properties: { hardness: 100, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:lava'),
    type: 'LAVA',
    properties: { hardness: 0, transparency: false, solid: false, emissive: true, friction: 0 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:obsidian'),
    type: 'OBSIDIAN',
    properties: { hardness: 100, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:coal_ore'),
    type: 'COAL_ORE',
    properties: { hardness: 75, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:iron_ore'),
    type: 'IRON_ORE',
    properties: { hardness: 75, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:gold_ore'),
    type: 'GOLD_ORE',
    properties: { hardness: 75, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:diamond_ore'),
    type: 'DIAMOND_ORE',
    properties: { hardness: 75, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:redstone_ore'),
    type: 'REDSTONE_ORE',
    properties: { hardness: 75, transparency: false, solid: true, emissive: true, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:lapis_ore'),
    type: 'LAPIS_ORE',
    properties: { hardness: 75, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:emerald_ore'),
    type: 'EMERALD_ORE',
    properties: { hardness: 75, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:deepslate_coal_ore'),
    type: 'DEEPSLATE_COAL_ORE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:deepslate_iron_ore'),
    type: 'DEEPSLATE_IRON_ORE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:deepslate_gold_ore'),
    type: 'DEEPSLATE_GOLD_ORE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:deepslate_diamond_ore'),
    type: 'DEEPSLATE_DIAMOND_ORE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:deepslate_redstone_ore'),
    type: 'DEEPSLATE_REDSTONE_ORE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: true, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:deepslate_lapis_ore'),
    type: 'DEEPSLATE_LAPIS_ORE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:deepslate_emerald_ore'),
    type: 'DEEPSLATE_EMERALD_ORE',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:coal_block'),
    type: 'COAL_BLOCK',
    properties: { hardness: 85, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:iron_block'),
    type: 'IRON_BLOCK',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:gold_block'),
    type: 'GOLD_BLOCK',
    properties: { hardness: 80, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:diamond_block'),
    type: 'DIAMOND_BLOCK',
    properties: { hardness: 95, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:redstone_block'),
    type: 'REDSTONE_BLOCK',
    properties: { hardness: 80, transparency: false, solid: true, emissive: true, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:lapis_block'),
    type: 'LAPIS_BLOCK',
    properties: { hardness: 80, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:emerald_block'),
    type: 'EMERALD_BLOCK',
    properties: { hardness: 90, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:planks'),
    type: 'PLANKS',
    properties: { hardness: 25, transparency: false, solid: true, emissive: false, friction: 0.6 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:sticks'),
    type: 'STICKS',
    properties: { hardness: 5, transparency: true, solid: false, emissive: false, friction: 0.2 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:crafting_table'),
    type: 'CRAFTING_TABLE',
    properties: { hardness: 40, transparency: false, solid: true, emissive: false, friction: 0.6 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:furnace'),
    type: 'FURNACE',
    properties: { hardness: 80, transparency: false, solid: true, emissive: false, friction: 0.8 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:torch'),
    type: 'TORCH',
    properties: { hardness: 1, transparency: true, solid: false, emissive: true, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:coal'),
    type: 'COAL',
    properties: { hardness: 1, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:wooden_sword'),
    type: 'WOODEN_SWORD',
    properties: { hardness: 10, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:wooden_pickaxe'),
    type: 'WOODEN_PICKAXE',
    properties: { hardness: 10, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:stone_pickaxe'),
    type: 'STONE_PICKAXE',
    properties: { hardness: 15, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:raw_iron'),
    type: 'RAW_IRON',
    properties: { hardness: 5, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:iron_ingot'),
    type: 'IRON_INGOT',
    properties: { hardness: 5, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:iron_pickaxe'),
    type: 'IRON_PICKAXE',
    properties: { hardness: 20, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:raw_gold'),
    type: 'RAW_GOLD',
    properties: { hardness: 5, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:gold_ingot'),
    type: 'GOLD_INGOT',
    properties: { hardness: 5, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:diamond'),
    type: 'DIAMOND',
    properties: { hardness: 5, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:redstone_dust'),
    type: 'REDSTONE_DUST',
    properties: { hardness: 1, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:lapis_lazuli'),
    type: 'LAPIS_LAZULI',
    properties: { hardness: 1, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:emerald'),
    type: 'EMERALD',
    properties: { hardness: 1, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
  new Block({
    id: makeBlockId('block:diamond_pickaxe'),
    type: 'DIAMOND_PICKAXE',
    properties: { hardness: 30, transparency: true, solid: false, emissive: false, friction: 0.1 },
    faces: defaultBlockFaces,
  }),
]
