import { Schema } from 'effect'

export const BlockTypeSchema = Schema.Literal(
  'AIR',
  'DIRT',
  'STONE',
  'WOOD',
  'GRASS',
  'SAND',
  'WATER',
  'LEAVES',
  'GLASS',
  'SNOW',
  'GRAVEL',
  'COBBLESTONE',
  'GRANITE',
  'DIORITE',
  'ANDESITE',
  'DEEPSLATE',
  'BEDROCK',
  'LAVA',
  'OBSIDIAN',
  'COAL_ORE',
  'IRON_ORE',
  'GOLD_ORE',
  'DIAMOND_ORE',
  'REDSTONE_ORE',
  'LAPIS_ORE',
  'EMERALD_ORE',
  'DEEPSLATE_COAL_ORE',
  'DEEPSLATE_IRON_ORE',
  'DEEPSLATE_GOLD_ORE',
  'DEEPSLATE_DIAMOND_ORE',
  'DEEPSLATE_REDSTONE_ORE',
  'DEEPSLATE_LAPIS_ORE',
  'DEEPSLATE_EMERALD_ORE',
  'COAL_BLOCK',
  'IRON_BLOCK',
  'GOLD_BLOCK',
  'DIAMOND_BLOCK',
  'REDSTONE_BLOCK',
  'LAPIS_BLOCK',
  'EMERALD_BLOCK',
  'PLANKS',
  'CRAFTING_TABLE',
  'FURNACE',
  'TORCH',
  'NETHERRACK',
  'NETHER_PORTAL',
  'FARMLAND',
  'WHEAT_CROP',
  // Redstone components (Phase 16)
  'REDSTONE_WIRE',
  'REDSTONE_TORCH',
  'LEVER',
  'STONE_BUTTON',
  'REPEATER',
  // Furniture / utility
  'BED',
  'ENCHANTING_TABLE',
  // The End dimension
  'END_STONE',
  'END_PORTAL_FRAME',
  'END_PORTAL',
  'CHORUS_FLOWER',
  'CHORUS_PLANT',
  'DRAGON_EGG',
  'END_CRYSTAL',
  'END_GATEWAY',
  'END_ROD',
  'END_STONE_BRICKS',
  'ENDER_CHEST',
  'PURPUR_BLOCK',
  'PURPUR_PILLAR',
  'PURPUR_SLAB',
  'PURPUR_STAIRS',
  'SHULKER_BOX',
  // Explosives
  'TNT',
  // Storage
  'CHEST',
  // Doors
  'DOOR',
  'DOOR_OPEN',
  // Nether / passable utility / plants
  'GLOWSTONE',
  'LADDER',
  'COBWEB',
  'SAPLING',
  'DANDELION',
  'POPPY',
  'BROWN_MUSHROOM',
  'RED_MUSHROOM',
  'TALL_GRASS',
  'FERN',
  'SUGAR_CANE',
  'CACTUS',
  'LILY_PAD',
  'ICE',
  'PRESSURE_PLATE',
  'STONE_SLAB',
  'OAK_STAIRS',
  'ANVIL',
  'CAULDRON',
  'FIRE',
  'WATER_CAULDRON'
)
export type BlockType = Schema.Schema.Type<typeof BlockTypeSchema>
