export * from '@domain/equipment/types'
export {
  EquipmentPieceSchema,
  EquipmentSetSchema,
  EquipmentTagSchema,
  assignBonusStats,
  carriedWeightPercentage,
  createEquipmentPiece,
  createEquipmentSet,
  emptyEquipmentSet,
  ensureFitsSlot,
  equipPiece,
  findPiece,
  promoteTier,
  unequipSlot,
  updatePieces,
  withUpdatedTimestamp,
  type EquipmentPiece,
  type EquipmentSet,
  type EquipmentTag,
  type Slots,
} from './aggregate'
export { analyseEquipmentSet, type EquipmentAnalysisSummary } from './domain_service'
export { EquipmentRepositoryTag, type EquipmentRepository } from './repository'
export {
  EquipmentSlotSchema,
  EquipmentStatsSchema,
  EquipmentTierSchema,
  allSlots,
  applyTierWeight,
  ensureSlotAllowed,
  ensureWeightWithinLimit,
  equipmentSlotLiterals,
  getSlotCategory,
  mergeStats,
  parseWeight,
  type EquipmentSlot,
  type EquipmentSlotLiteral,
  type EquipmentStats,
  type EquipmentTier,
} from './value_object'
