name: AI Agent Task
description: AI Coding Agent自動実行用 構造化タスク
title: "[TASK-ID] タスク名"
labels: ["ai-agent", "task", "execution-plan", "auto-executable"]
assignees: ["@me"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 AI Coding Agent自動実行タスク

        このテンプレートはClaude Agentが `claude "Issue #N を実装して"` で自動実行できる構造化タスクを作成します。

        **実行コマンド**: `claude "Issue #[番号] を実装して"`

  - type: input
    id: task-id
    attributes:
      label: Task ID
      description: ROADMAPのタスクID (P0-001形式)
      placeholder: P0-001
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 実装複雑度
      description: AI Agentが判断する技術的複雑度
      options:
        - "1 - Very Simple (設定変更レベル)"
        - "2 - Simple (単純な関数実装)"
        - "3 - Easy (基本的な機能実装)"
        - "4 - Medium-Easy (複数ファイル実装)"
        - "5 - Medium (標準的な機能実装)"
        - "6 - Medium-Hard (複雑なロジック)"
        - "7 - Hard (アーキテクチャ変更)"
        - "8 - Very Hard (大規模リファクタリング)"
        - "9 - Expert (新技術・パターン導入)"
        - "10 - Extreme (フルスタック実装)"
    validations:
      required: true

  - type: dropdown
    id: ai-guidance
    attributes:
      label: AI実装ガイダンスレベル
      description: AI Agentが必要とする指示の詳細度
      options:
        - "Minimal - 基本要件のみ"
        - "Standard - 通常レベルの指示"
        - "Detailed - 詳細な実装指示"
        - "Expert - 高度な技術指示と制約"
    validations:
      required: true

  - type: textarea
    id: ai-context
    attributes:
      label: AI実装コンテキスト
      description: AI Agentが参照すべきドキュメント（docs/）を指定
      placeholder: |
        参照: docs/reference/architecture/constraints.md
    validations:
      required: true

  - type: textarea
    id: execution-phases
    attributes:
      label: 実行ステップ（AI Agent自動実行用）
      description: Claude Agentが参照すべきドキュメントリンクと実行手順
      placeholder: |
        参照: docs/how-to/development/implementation-steps.md
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: Acceptance Criteria（自動検証）
      description: Claude Agentが自動実行・検証する完了条件
      placeholder: |
        参照: docs/reference/quality/acceptance-criteria.md
    validations:
      required: true

  - type: textarea
    id: verification-commands
    attributes:
      label: 自動実行コマンドシーケンス
      description: Claude Agentが順次実行する検証コマンド（失敗時は自動修正試行）
      placeholder: |
        参照: docs/how-to/development/quality-checks.md
    validations:
      required: true


