name: AI Agent Task
description: AI Coding Agent自動実行用 構造化タスク
title: "[TASK-ID] タスク名"
labels: ["ai-agent", "task", "execution-plan", "auto-executable"]
assignees: ["@me"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 AI Coding Agent自動実行タスク

        このテンプレートはClaude Agentが `claude "Issue #N を実装して"` で自動実行できる構造化タスクを作成します。

        **実行コマンド**: `claude "Issue #[番号] を実装して"`

  - type: input
    id: task-id
    attributes:
      label: Task ID
      description: ROADMAPのタスクID (P0-001形式)
      placeholder: P0-001
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 実装複雑度
      description: AI Agentが判断する技術的複雑度
      options:
        - "1 - Very Simple (設定変更レベル)"
        - "2 - Simple (単純な関数実装)"
        - "3 - Easy (基本的な機能実装)"
        - "4 - Medium-Easy (複数ファイル実装)"
        - "5 - Medium (標準的な機能実装)"
        - "6 - Medium-Hard (複雑なロジック)"
        - "7 - Hard (アーキテクチャ変更)"
        - "8 - Very Hard (大規模リファクタリング)"
        - "9 - Expert (新技術・パターン導入)"
        - "10 - Extreme (フルスタック実装)"
    validations:
      required: true

  - type: dropdown
    id: ai-guidance
    attributes:
      label: AI実装ガイダンスレベル
      description: AI Agentが必要とする指示の詳細度
      options:
        - "Minimal - 基本要件のみ"
        - "Standard - 通常レベルの指示"
        - "Detailed - 詳細な実装指示"
        - "Expert - 高度な技術指示と制約"
    validations:
      required: true

  - type: textarea
    id: ai-context
    attributes:
      label: AI実装コンテキスト
      description: AI Agentが参照すべきドキュメント（docs/）を指定
      placeholder: |
        参照: docs/reference/architecture/constraints.md
    validations:
      required: true

  - type: dropdown
    id: context7-libraries
    attributes:
      label: Context7活用ライブラリ
      description: 実装で使用する主要ライブラリ（Context7で最新仕様確認）
      options:
        - "Effect-TS (@effect/schema, @effect/io など)"
        - "Three.js (3D graphics)"
        - "Vite (build tool)"
        - "Vitest (testing)"
        - "TypeScript (latest features)"
        - "その他（実行ステップで明記）"
        - "ライブラリ使用なし"
    validations:
      required: true

  - type: textarea
    id: docs-updates
    attributes:
      label: ドキュメント更新要件
      description: 実装完了後にdocs/へ追加すべき新しい仕様・パターン
      placeholder: |
        - 新しい実装パターンの記録 (docs/patterns/)
        - API仕様の更新 (docs/reference/)
        - 設定変更の記録 (docs/how-to/)
        - アーキテクチャ決定の記録 (docs/explanations/)
    validations:
      required: false

  - type: textarea
    id: execution-phases
    attributes:
      label: 実行ステップ（AI Agent自動実行用）
      description: Claude Agentが参照すべきドキュメントリンクと実行手順
      placeholder: |
        ## 実行フロー（8段階 + 前後処理）

        ### Pre-Step: 実装前確認
        1. `list_memories` - 既存実装パターン確認
        2. `@docs/` 設計方針・実装方針確認 (指定ドキュメント必読)
        3. Context7でライブラリ最新仕様確認

        ### Step 1: 事前調査・分析
        参照: docs/how-to/development/analysis-phase.md

        ### Step 2: ディレクトリ構造作成
        参照: docs/reference/architecture/directory-structure.md

        ### Step 3: 型定義・データ構造
        参照: docs/reference/patterns/effect-ts-patterns.md

        ### Step 4: Service実装
        参照: docs/reference/patterns/service-layer-patterns.md

        ### Step 5: ECSシステム統合
        参照: docs/reference/architecture/ecs-integration.md

        ### Step 6: テスト実装
        参照: docs/how-to/testing/vitest-patterns.md

        ### Step 7: 統合・エクスポート
        参照: docs/reference/patterns/module-exports.md

        ### Step 8: 品質確認・最適化
        参照: docs/how-to/development/quality-gates.md

        ### Post-Step: 実装後処理
        1. `@docs/` へ新パターン記録
        2. `write_memory` で重要パターン保存
        3. 検証コマンド実行
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: Acceptance Criteria（自動検証）
      description: Claude Agentが自動実行・検証する完了条件
      placeholder: |
        参照: docs/reference/quality/acceptance-criteria.md
    validations:
      required: true

  - type: textarea
    id: verification-commands
    attributes:
      label: 自動実行コマンドシーケンス
      description: Claude Agentが順次実行する検証コマンド（失敗時は自動修正試行）
      placeholder: |
        参照: docs/how-to/development/quality-checks.md
    validations:
      required: true


