name: バグ報告
description: バグ報告用 Issue
title: "[Bug] 簡潔なバグ説明"
labels: ["bug", "japanese"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: 重要度
      options:
        - Critical (システム停止)
        - High (主要機能影響)
        - Medium (部分的影響)
        - Low (軽微な問題)
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: 現在の動作
      description: 何が起こっているか
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
      description: 何が起こるべきか
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 再現手順
      placeholder: |
        1. ...を実行
        2. ...をクリック
        3. エラーが発生
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 環境情報
      placeholder: |
        - OS: macOS 14.x
        - Node: 20.x
        - Browser: Chrome 120.x