// Performance Constants
export {
  TARGET_FPS,
  MAX_DELTA_TIME,
  PERFORMANCE_SAMPLE_SIZE,
  MAX_CACHED_CHUNKS,
  MEMORY_CLEANUP_THRESHOLD,
  GC_TRIGGER_INTERVAL,
  MAX_WORKER_THREADS,
  WORKER_TASK_TIMEOUT,
  WORKER_BATCH_SIZE,
  MAX_DRAW_CALLS,
  FRUSTUM_CULLING_MARGIN,
  LOD_DISTANCE_THRESHOLD,
  MAX_CONCURRENT_REQUESTS,
  REQUEST_TIMEOUT,
  RETRY_ATTEMPTS,
  TEXTURE_CACHE_SIZE,
  MESH_CACHE_SIZE,
  SHADER_CACHE_SIZE,
} from './performance'

// Physics Constants
export {
  PLAYER_SPEED,
  SPRINT_MULTIPLIER,
  JUMP_FORCE,
  TERMINAL_VELOCITY,
  FRICTION,
  GRAVITY,
  DECELERATION,
  MIN_VELOCITY_THRESHOLD,
  PLAYER_HEIGHT,
  COLLISION_MARGIN,
  MAX_COLLISION_ITERATIONS,
  PLAYER_COLLIDER,
  BLOCK_COLLIDER,
} from './physics'

// UI Constants
export {
  KEY_REPEAT_DELAY,
  KEY_REPEAT_RATE,
  MOUSE_SENSITIVITY,
  TOUCH_SENSITIVITY,
  DEBUG_PANEL_WIDTH,
  DEBUG_PANEL_HEIGHT,
  INVENTORY_SLOTS_PER_ROW,
  HOTBAR_SLOTS,
  DEFAULT_ANIMATION_DURATION,
  FADE_ANIMATION_DURATION,
  SLIDE_ANIMATION_DURATION,
  COLORS,
  Z_INDEX,
} from './ui'

// World Constants
export { CHUNK_SIZE, CHUNK_HEIGHT, WATER_LEVEL, WORLD_DEPTH, MIN_WORLD_Y, Y_OFFSET, RENDER_DISTANCE, NOISE_SCALE, TERRAIN_HEIGHT_MULTIPLIER, CAVE_THRESHOLD } from './world'

// Texture Constants
export {
  TEXTURE_TILE_SIZE,
  ATLAS_WIDTH_IN_TILES,
  ATLAS_SIZE,
  MAX_MIPMAPS,
  ANISOTROPY,
  COMPRESSION_ENABLED,
  LAZY_LOADING,
  PRELOAD_ESSENTIALS,
  CACHE_SIZE,
  STREAMING_ENABLED,
} from './texture'
