// Performance Constants
export {
  TARGET_FPS,
} from './performance'

// Physics Constants
export {
  PLAYER_SPEED,
  SPRINT_MULTIPLIER,
  JUMP_FORCE,
  TERMINAL_VELOCITY,
  FRICTION,
  GRAVITY,
  DECELERATION,
  MIN_VELOCITY_THRESHOLD,
  PLAYER_HEIGHT,
  COLLISION_MARGIN,
  MAX_COLLISION_ITERATIONS,
  PHYSICS_TIME_STEP,
  MAX_PHYSICS_SUBSTEPS,
  PLAYER_COLLIDER,
  BLOCK_COLLIDER,
  type SimpleCollider,
} from './physics'


// World Constants
export { CHUNK_SIZE, CHUNK_HEIGHT, WATER_LEVEL, WORLD_DEPTH, MIN_WORLD_Y, Y_OFFSET, RENDER_DISTANCE, NOISE_SCALE, TERRAIN_HEIGHT_MULTIPLIER, CAVE_THRESHOLD } from './world'

// Texture Constants
export {
  TEXTURE_TILE_SIZE,
  ATLAS_WIDTH_IN_TILES,
  ATLAS_SIZE,
  MAX_MIPMAPS,
  ANISOTROPY,
  COMPRESSION_ENABLED,
  LAZY_LOADING,
  PRELOAD_ESSENTIALS,
  CACHE_SIZE,
  STREAMING_ENABLED,
} from './texture'
