// Error types and creation functions
export {
  // Core error system
  createErrorContext,
  logError,
  createRecoveryHandler,
  createTaggedError,
  ErrorAggregator,
  type RecoveryStrategy,
  type ErrorContext,
  type BaseErrorData,
  type ErrorAggregatorState,
  // Base errors
  GameError,
  createGameError,
  DomainError,
  createDomainError,
  EntityError,
  createEntityError,
  ComponentError,
  createComponentError,
  WorldError,
  createWorldError,
  PhysicsError,
  createPhysicsError,
  SystemError,
  createSystemError,
  ResourceError,
  createResourceError,
  RenderingError,
  createRenderingError,
  NetworkError,
  createNetworkError,
  InputError,
  createInputError,
  ErrorChain,
  createErrorChain,
  validateErrorHierarchy,
  getErrorAncestry,
  // Entity errors
  EntityNotFoundError,
  EntityAlreadyExistsError,
  InvalidEntityStateError,
  EntityCreationError,
  EntityDestructionError,
  EntityArchetypeMismatchError,
  StaleEntityReferenceError,
  EntityLimitExceededError,
  // Component errors
  ComponentNotFoundError,
  InvalidComponentDataError,
  ComponentAlreadyExistsError,
  ComponentSerializationError,
  ComponentDeserializationError,
  ComponentTypeMismatchError,
  ComponentDependencyError,
  ComponentLifecycleError,
  ComponentCapacityError,
  // World errors
  ChunkNotLoadedError,
  InvalidPositionError,
  BlockNotFoundError,
  InvalidBlockTypeError,
  WorldStateError,
  ArchetypeNotFoundError,
  QuerySingleResultNotFoundError,
  ComponentDecodeError,
  ChunkGenerationError,
  WorldSaveError,
  WorldLoadError,
  BlockPlacementError,
  WorldTickError,
  // Physics errors
  CollisionDetectionError,
  createCollisionDetectionError,
  PhysicsSimulationError,
  createPhysicsSimulationError,
  RigidBodyError,
  createRigidBodyError,
  GravityError,
  createGravityError,
  ConstraintViolationError,
  createConstraintViolationError,
  RaycastError,
  createRaycastError,
  PhysicsMaterialError,
  createPhysicsMaterialError,
  // System errors
  SystemExecutionError,
  InvalidSystemStateError,
  SystemInitializationError,
  SystemDependencyError,
  SystemPerformanceError,
  QueryExecutionError,
  EmptyQueryResultError,
  QueryValidationError,
  SystemSchedulerError,
  // Worker errors
  WorkerCommunicationError,
  WorkerTaskFailedError,
  WorkerInitializationError,
  WorkerPoolExhaustedError,
  WorkerTerminatedError,
  WorkerDataTransferError,
  WorkerTimeoutError,
  // Rendering errors
  TextureNotFoundError,
  MaterialNotFoundError,
  ShaderCompilationError,
  BufferAllocationError,
  RenderTargetError,
  MeshDataError,
  GraphicsContextError,
  // Resource errors
  ResourceNotFoundError,
  ResourceLoadError,
  ValidationError,
  ResourceCacheError,
  UnsupportedFormatError,
  InputNotAvailableError,
  AssetBundleError,
  ResourcePermissionError,
} from '@domain/errors/error-exports'

// Schema validation errors  
export {
  SchemaValidationError,
  createSchemaValidationError,
  UnknownTypeError,
  createUnknownTypeError,
  TypeGuardError,
  createTypeGuardError,
  ExternalDataValidationError,
  DeserializationError,
  TypeAssertionError,
  ValidationHelpers,
  SchemaValidationUtils,
  withValidation,
  createValidationError,
  validateError,
  ValidationErrorValidation
} from '@domain/errors/validation-errors'

// Error utilities
export { ErrorUtils, type ErrorPatternMatcher, type ErrorRecoveryStrategy, type ErrorAnalysisResult, type ErrorReport, type ValidationResult } from '@domain/errors/error-utils'
