export declare const BIOME_SCALE = 0.005;
export declare const HUMIDITY_WORLD_OFFSET = 10000;
export declare const TEMP_COLD = 0.3;
export declare const TEMP_HOT = 0.7;
export declare const HUM_DRY = 0.3;
export declare const HUM_WET = 0.6;
export declare const HUM_VERY_DRY = 0.15;
export declare const HUM_VERY_WET = 0.85;
export declare const HUM_JUNGLE = 0.72;
export declare const TEMP_JUNGLE = 0.78;
export declare const HUM_TAIGA = 0.55;
export declare const HUM_MOUNTAINS = 0.4;
export declare const HUM_SAVANNA_MIN = 0.22;
export declare const RIVER_NOISE_SCALE = 0.0035;
export declare const RIVER_WORLD_OFFSET = 20000;
export declare const RIVER_CENTER = 0.5;
export declare const RIVER_HALF_WIDTH = 0.055;
//# sourceMappingURL=biome-classifier.config.d.ts.map