export type { FrameAnimalInteractionServices } from './frame-interaction-service-types/animal'
export type { FrameArmorEquipInteractionServices } from './frame-interaction-service-types/armor'
export type { FrameBedInteractionServices } from './frame-interaction-service-types/bed'
export type { FrameBowInteractionServices } from './frame-interaction-service-types/bow'
export type { FrameBucketInteractionServices } from './frame-interaction-service-types/bucket'
export type { FrameCreativePickInteractionServices } from './frame-interaction-service-types/creative-pick'
export type { FrameDoorInteractionServices } from './frame-interaction-service-types/door'
export type { FrameEnchantingTableInteractionServices } from './frame-interaction-service-types/enchanting-table'
export type { FrameFishingRodInteractionServices } from './frame-interaction-service-types/fishing-rod'
export type { FrameFlintAndSteelInteractionServices } from './frame-interaction-service-types/flint-and-steel'
export type { FrameFoodConsumptionInteractionServices } from './frame-interaction-service-types/food-consumption'
export type { FrameHotbarHudServices, FrameHotbarInputServices } from './frame-interaction-service-types/hotbar'
export type { FrameRedstoneInteractionServices } from './frame-interaction-service-types/redstone'
export type { FrameRightClickInteractionServices } from './frame-interaction-service-types/right-click'
export type { FrameUnequipArmorInteractionServices } from './frame-interaction-service-types/unequip-armor'
