import {
  makeBiomeService,
  makeBlockService,
  makeChunkManagerService,
  makeChunkMeshService,
  makeCropGrowthService,
  makeDroppedItemRenderer,
  makeDroppedXpOrbRenderer,
  makeEntityRenderer,
  makeEquipmentService,
  makeFluidService,
  makeHotbarService,
  makeInventoryService,
  makeNetherService,
  makeParticleSystem,
  makePerfHud,
  makeWeatherService,
  makeWorldRendererService,
} from '../world'

export const makeWorldServices = () => ({
  blockService: makeBlockService(),
  hotbarService: makeHotbarService(),
  chunkManagerService: makeChunkManagerService(),
  inventoryService: makeInventoryService(),
  equipmentService: makeEquipmentService(),
  worldRendererService: makeWorldRendererService(),
  droppedItemRenderer: makeDroppedItemRenderer(),
  droppedXpOrbRenderer: makeDroppedXpOrbRenderer(),
  entityRenderer: makeEntityRenderer(),
  chunkMeshService: makeChunkMeshService(),
  particleSystem: makeParticleSystem(),
  weatherService: makeWeatherService(),
  biomeService: makeBiomeService(),
  fluidService: makeFluidService(),
  netherService: makeNetherService(),
  cropGrowthService: makeCropGrowthService(),
  perfHud: makePerfHud(),
})
