name: test and deploy

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    name: test and deploy
    runs-on: ubuntu-latest
    steps:
    # setup
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: setup Node
      uses: actions/setup-node@v2
    - name: update npm
      run: sudo npm i -g npm
    - name: Install Dependencies
      run: npm ci

    # test
    - name: lint
      run: npm run lint
    - name: tsc
      run: npm run tsc
    - name: test
      run: npm run test
    - name: Build
      run: npm run build

    # deploy
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
